# Generated by Django 4.0 on 2021-12-29 05:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120)),
                ('post_name', models.CharField(max_length=120)),
                ('cv', models.FileField(upload_to='web/career/files/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('person', models.CharField(choices=[('default', 'SELECT PERSON'), ('person_1', 'FADHIL FAEZ'), ('person_2', 'ADNAN LATHEEF'), ('person_3', 'PV ANFAS'), ('person_4', 'YAQOOB K C'), ('person_5', 'PRABHINA')], default='default', max_length=12)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='web/Home/')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'business',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Community',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Upcoming Project',
                'verbose_name_plural': 'Upcoming Project',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instegram', models.CharField(blank=True, max_length=120, null=True)),
                ('facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'social links',
                'verbose_name_plural': 'social links',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='web/teams/')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'leadership team',
                'verbose_name_plural': 'leadership Teams',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='web.team')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('job_name', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(default='web/career/default.jpg', upload_to='web/career/')),
                ('job_description', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.business')),
            ],
            options={
                'verbose_name': 'career',
                'verbose_name_plural': 'career',
                'ordering': ('date',),
            },
        ),
    ]
